# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'notifhandler', :path => '../notifhandler'
#  pod 'OneSignal', '>= 2.6.2', '< 3.0'
end

target 'NotificationContent' do
    use_frameworks!
    pod 'notifhandler', :path => '../notifhandler'
end

target 'Notification Service' do
    use_frameworks!
    pod 'notifhandler', :path => '../notifhandler'
end
